# Generated by Django 3.0.2 on 2020-08-06 10:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='like',
            new_name='Likes',
        ),
    ]
